### ISSUE TITLE
`Strongbolt.setup` fails if 'strongbolt_capabilities' table doesn't exist

### ISSUE THREAD

**Issue by ojab** [605data/strongbolt#36]
`rails g strongbolt:install && rake db:migrate` from README works fine, but preferred way in rails 5+ is `rails db:migrate`, which fails with:
```
$ bundle exec rails db:migrate
rails aborted!
ActiveRecord::StatementInvalid: Could not find table 'strongbolt_capabilities'
/home/ojab/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:417:in `table_structure'
/home/ojab/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:166:in `columns'
/home/ojab/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
/home/ojab/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
```
because `Strongbolt.setup` requires 'strongbolt_capabilities'  table and it's called in initializer. Similar cases (like `rails db:create db:migrate` with empty DB) also fail.

So far I don't know how proper fix would look, maybe we should initialize Strongbolt lazily.

**Comment by tobithiel** [comment]
Interesting, seems like the new tasks work a little different. Could you post the full stack trace?
