### ISSUE TITLE
Dependencies seem to be outdated for Rails 5.2

### ISSUE THREAD

**Issue by onkeld** [605data/strongbolt#45]
I'm finally back with trying out strongbolt for a new app.
I am running on Rails 5.2.0 and can't install strongbolt via gems anymore.

Apparently, the current strongbolt gem has a dependency of awesome_nested_set (~> 3.0.0) which gets resolved to a version of the gem in the 3.0 branch which is not compatible with rails 5.2 anymore.
The gem for awesome_nested_set is already available in a version 3.1(.4). According to the developers, this version is rails 5.2 compatible.
I installed this one without problems in my rails app.

However the strongbolt dependency explicitly requiring a 3.0.x version of the gem breaks the app.

Would it be possible to relax the dependency so that a 3.1 version of the gem is acceptable?

**Comment by onkeld** [comment]
I just checked the code in the repository.
Apparently this was already addressed in the master branch as awesome_nested_set is required in version ~>3.1.0.
Apparently, only the gem hasn't been updated...

**Comment by onkeld** [comment]
Things are a bit funky...

I also found that the gem is actually updated.
However, when I just include gem 'strongbolt' in my gemfile, this resolves to version 0.3.6 instead of 0.3.15
If I explicitly ask for version 0.3.15, then the awesome_nested_set dependency works.
However, now the simple_form dependency crashes the bundle as it resolves to 3.0.1 which requires actionpack <4.1.
However, there is a version 4 of simple_form available.
If I explicitly install this, then strongbolt can't be installed as it requires a simple_form version of 3.x apparently.
Seems like an update is needed here...

**Comment by tobithiel** [comment]
@onkeld We would be happy to merge a pull request 😃

**Comment by matissg** [comment]
@tobithiel  I'm trying to test your latest commit, however it seems we will have conflict with ActiveStorage if anyone tries to use it. I'm using ActiveStorage so I run into [undefined method `has_one_attached' issue](https://github.com/rails/rails/issues/32933).

I believe more people may want to start using ActiveStorage, so this might be a problem in future. In general as I understand we should not use models in initialisers, an example [solution for different gem](https://github.com/epfl-exts/rails-gdpr-export/issues/1).

**Comment by tobithiel** [comment]
@matissg You're talking about the commits in #46 ? Without a stack trace and/or a bit of code that reproduces the issue, there's not much I can do.

**Comment by matissg** [comment]
@tobithiel  Yes, I downloaded and locally installed those last commits. In my model I have this:

```
class Common::Company < ApplicationRecord
  has_one_attached :image
end
```

in `initializers/strongbolt.rb` I have `config.tenants = "Common::Company"`
so later on booting I get this one:

```
=> Booting Puma
=> Rails 5.2.1 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
        108: from bin/rails:4:in `<main>'
        107: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
        106: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
        105: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
        104: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        103: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        102: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        101: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        100: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         99: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
         98: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
         97: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
         96: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         95: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         94: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         93: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
         92: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
         91: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
         90: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
         89: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
         88: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
         87: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
         86: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
         85: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
         84: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
         83: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
         82: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
         81: from config.ru:in `<main>'
         80: from config.ru:in `new'
         79: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
         78: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
         77: from config.ru:3:in `block in <main>'
         76: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
         75: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
         74: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         73: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         72: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         71: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         70: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         69: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
         68: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         67: from /mnt/c/sites/ad8/config/environment.rb:5:in `<main>'
         66: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
         65: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
         64: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
         63: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
         62: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
         61: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
         60: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
         59: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
         58: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
         57: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `call'
         56: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
         55: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
         54: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
         53: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
         52: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
         51: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
         50: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
         49: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
         48: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
         47: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
         46: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
         45: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `each'
         44: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
         43: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
         42: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
         41: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
         40: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
         39: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         38: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
         37: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
         36: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
         35: from /mnt/c/sites/ad8/config/initializers/strongbolt.rb:1:in `<main>'
         34: from /mnt/c/sites/ad8/vendor/gems/strongbolt/lib/strongbolt.rb:117:in `setup'
         33: from /mnt/c/sites/ad8/config/initializers/strongbolt.rb:20:in `block in <main>'
         32: from /mnt/c/sites/ad8/vendor/gems/strongbolt/lib/strongbolt/configuration.rb:38:in `tenants='
         31: from /mnt/c/sites/ad8/vendor/gems/strongbolt/lib/strongbolt/configuration.rb:38:in `each'
         30: from /mnt/c/sites/ad8/vendor/gems/strongbolt/lib/strongbolt/configuration.rb:38:in `block in tenants='
         29: from /mnt/c/sites/ad8/vendor/gems/strongbolt/lib/strongbolt/configuration.rb:52:in `add_tenant'
         28: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
         27: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/inflector/methods.rb:281:in `constantize'
         26: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/inflector/methods.rb:281:in `inject'
         25: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/inflector/methods.rb:281:in `each'
         24: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/inflector/methods.rb:285:in `block in constantize'
         23: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/inflector/methods.rb:285:in `const_get'
         22: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:193:in `const_missing'
         21: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
         20: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
         19: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
         18: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:506:in `load_missing_constant'
         17: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
         16: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
         15: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
         14: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:352:in `require_or_load'
         13: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
         12: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
         11: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
         10: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
          9: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
          8: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:369:in `block in require_or_load'
          7: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:471:in `load_file'
          6: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:657:in `new_constants_in'
          5: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:472:in `block in load_file'
          4: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
          3: from /home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
          2: from /mnt/c/sites/ad8/app/models/common/company.rb:26:in `<main>'
          1: from /mnt/c/sites/ad8/app/models/common/company.rb:28:in `<class:Company>'
/home/matis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_one_attached' for #<Class:0x00007fffef58d238> (NoMethodError)

```

**Comment by tobithiel** [comment]
@matissg Could you please share a one file Rails application to reproduce this? There some docs about them here for example: https://christoph.luppri.ch/articles/rails/single-file-rails-applications-for-fun-and-bug-reporting/
